Repository appsignal/design-language, pull requests merged in 2019-08, with the labels that each got.

#14 First colors, spacing and typography
  tokens/colors.json
  tokens/font-family.json
  tokens/font.json
  tokens/index.json
  tokens/spacing.json
Labels: design

#16 Borders, colors, fonts
  tokens/borders.json
  tokens/colors.json
  tokens/font.json
  tokens/index.json
Labels: design

#20 Use major third typographic scale
  tokens/font.json
Labels: discuss, enhancement

#23 Secondary button + button sizes
  src/components/button.css
Labels: design

#28 Build tokens on every command
  package.json
Labels: chore, dev happiness

#25 Add prototype type and spacing scale
  src/components/navigation.css
  src/components/topbar.css
  src/elements/typography.css
  src/generated/index.custom-properties.css
  src/generic/typography.css
  src/index.css
  src/objects/grid.css
  src/objects/layout.css
  tokens/spacing.json
Labels: design

#30 Remove .vscode folder
  .gitignore
  .vscode/settings.json
Labels: chore, dev happiness

#31 Add classes for Background and Text colors
  src/components/button.css
  src/components/navigation.css
  src/components/topbar.css
  src/elements/typography.css
  src/generated/index.custom-properties.css
  src/generic/typography.css
  src/index.css
  src/utils/bg-color.css
  src/utils/text-color.css
  tokens/colors.json
Labels: chore

#36 DL: Inline text
  src/index.css
  src/utils/text/color.css
  src/utils/text/decoration.css
  src/utils/text/misc.css
  src/utils/text/size.css
  src/utils/text/style.css
  src/utils/text/transform.css
  src/utils/text/weight.css
Labels: design

#38 Add Flexbox utilities
  src/index.css
  src/utils/flexbox.css
Labels: chore

#40 Add spacing utilities
  src/utils/spacing/margin.css
Labels: chore

#34 Add @extend functionality
  package.json
  postcss.config.js
  src/components/button.css
  stylelint.config.js
  yarn.lock
Labels: chore, enhancement

#37 DL: Add box style, spacing, text-align
  src/components/box.css
  src/index.css
  src/utils/shadow.css
  src/utils/text-color.css
  src/utils/text/align.css
Labels: design

#35 DL: Add responsive grid
  src/generated/index.custom-properties.css
  src/objects/grid.css
  src/utils/grid.css
  tokens/spacing.json
Labels: design

#42 Add Semaphore config
  .nvmrc
  .semaphore/semaphore.yml
Labels: chore, dev happiness

#43 Make Husky Stylelinting follow our rules
  package.json
  src/generated/index.custom-properties.css
  stylelint.config.js
Labels: chore, dev happiness

#44 Add @responsive helper to generate responsive CSS
  plugins/atResponsive.js
  postcss.config.js
  src/utils/grid.css
  stylelint.config.js
Labels: chore, dev happiness

#46 Convert utilities to non-bem
  src/components/button.css
  src/components/navigation.css
  src/components/topbar.css
  src/utils/bg-color.css
  src/utils/flexbox.css
  src/utils/layout.css
  src/utils/spacing/margin.css
  src/utils/text/align.css
  src/utils/text/color.css
  src/utils/text/decoration.css
  src/utils/text/misc.css
  src/utils/text/size.css
  src/utils/text/style.css
  src/utils/text/transform.css
  src/utils/text/weight.css
Labels: chore, dev happiness

#47 Split out Flexbox utilities
  src/index.css
  src/utils/flexbox/align-content.css
  src/utils/flexbox/align-items.css
  src/utils/flexbox/flex.css
  src/utils/flexbox/justify-content.css
  src/utils/layout.css
Labels: chore, dev happiness

#49 Use a spacing scale that is a factor of 0.25
  src/components/box.css
  src/components/navigation.css
  src/components/topbar.css
  src/elements/typography.css
  src/generated/index.custom-properties.css
  src/utils/spacing/margin.css
  tokens/spacing.json
Labels: enhancement

#48 Add Padding utilities
  src/components/box.css
  src/components/button.css
  src/components/navigation.css
  src/elements/typography.css
  src/index.css
  src/utils/spacing/padding.css
Labels: enhancement

#51 Add dist folder when committing
  .gitignore
  dist/design-language.css
  package.json
Labels: chore
